import { Bhk } from "@prisma/client";

export const CITIES = ["Chandigarh", "Mohali", "Zirakpur", "Panchkula", "Other"] as const;
export const PROPERTY_TYPES = ["Apartment", "Villa", "Plot", "Office", "Retail"] as const;
export const BHK_OPTIONS = ["One", "Two", "Three", "Four", "Studio"] as const;
export const PURPOSES = ["Buy", "Rent"] as const;
export const TIMELINES = ["ZeroToThreeMonths", "ThreeToSixMonths", "OverSixMonths", "Exploring"] as const;
export const SOURCES = ["Website", "Referral", "Walk-in", "Call", "Other"] as const;
export const STATUSES = ["New", "Qualified", "Contacted", "Visited", "Negotiation", "Converted", "Dropped"] as const;

export type Buyer = { id: string;
    fullName: string;
    updatedAt: string;
    email: string;
    phone: string;
    city: string;
    propertyType: string;
    bhk: Bhk;
    purpose: string;
    budgetMin: string;
    budgetMax: string;
    timeline: string;
    source: string;
    status: string;
    notes: string;
    tags: string[];
    ownerId: string;
    date: string;
};
export type BuyerHistory = { id: string; changedAt: string; changedById: string; diff: Record<string, unknown> };
export type User = { id: string; isAdmin?: boolean };